"""Artefact ingest API tests (SPEC 9.1, 16).

Uploads the bundled synthetic sample PDF (dataset/samples, generated by
scripts/make_samples.py) through POST /api/intake/artefact and asserts
the honest extraction method, the SHA-256 intake hash over the artefact
bytes, the planted identifiers from rule-augmented NER, and the
artefact.ingested append on the audit chain.

The PDF carries a real text layer, so this test does not need the
tesseract binary; it skips only when the bundled sample is absent.
"""

import hashlib
import os

import pytest
from fastapi.testclient import TestClient

import paritran.api.main as main
import paritran.api.runstore as runstore
from paritran.api import deps
from paritran.config import get_settings
from paritran.db.seed import seed_users

from _paths import SAMPLES_DIR

pytestmark = pytest.mark.db

TEST_JWT_SECRET = "test-only-jwt-secret-64-chars-not-a-real-credential-0000000000"

PDF_SAMPLE = SAMPLES_DIR / "complaint_sample.pdf"

# Planted by scripts/make_samples.py (same set tests/test_ingest_ocr.py
# asserts at the engine level).
PLANTED = {
    ("9876543210", "phone"),
    ("fraudster@upi", "upi"),
    ("203.0.113.7", "ipv4"),
    ("123456789012", "account"),
}

needs_sample = pytest.mark.skipif(
    not PDF_SAMPLE.is_file(),
    reason="bundled synthetic sample missing (scripts/make_samples.py)",
)


@pytest.fixture
def api(db, monkeypatch):
    monkeypatch.setenv("DATABASE_URL", db.app_dsn)
    monkeypatch.setenv("JWT_SECRET", TEST_JWT_SECRET)
    get_settings.cache_clear()
    seed_users(get_settings())
    monkeypatch.setattr(runstore, "_MAPPER_CACHE", [None])
    deps.limiter.reset()
    with TestClient(main.app) as client:
        yield client
    get_settings.cache_clear()


def _token(client, username: str, password_var: str) -> dict:
    response = client.post(
        "/api/auth/login",
        json={"username": username, "password": os.environ[password_var]},
    )
    assert response.status_code == 200, response.text
    return {"Authorization": f"Bearer {response.json()['access_token']}"}


@needs_sample
def test_pdf_artefact_ingest_end_to_end(api):
    officer = _token(api, "officer1", "OFFICER1_PASSWORD")
    raw = PDF_SAMPLE.read_bytes()

    response = api.post(
        "/api/intake/artefact",
        files={"file": ("complaint_sample.pdf", raw, "application/pdf")},
        headers=officer,
    )
    assert response.status_code == 200, response.text
    body = response.json()

    # Intake hash is SHA-256 over the artefact bytes, verifiable here.
    assert body["intake_hash"] == hashlib.sha256(raw).hexdigest()
    # Honest method label: the bundled PDF has a text layer, no OCR ran.
    assert body["method"] == "pdf-text"
    assert body["pages"] == 1

    got = {(i["identifier"], i["kind"]) for i in body["identifiers"]}
    assert PLANTED <= got, f"planted identifiers missing: {PLANTED - got}"

    assert body["text_excerpt"]
    assert len(body["text_excerpt"]) <= 500

    # artefact.ingested landed on the audit chain with the same hash.
    chain = api.get(
        "/api/audit/chain", params={"limit": 1000}, headers=officer
    ).json()
    row = next(r for r in chain["rows"] if r["seq"] == body["audit_seq"])
    assert row["action"] == "artefact.ingested"
    assert row["actor"] == "officer1"
    assert row["payload"]["intake_hash"] == body["intake_hash"]
    assert row["payload"]["method"] == "pdf-text"
    assert row["payload"]["n_identifiers"] == len(body["identifiers"])

    # The chain still verifies after the append.
    verify = api.get("/api/audit/verify", headers=officer)
    assert verify.json()["ok"] is True


@needs_sample
def test_artefact_requires_officer_role(api):
    auditor = _token(api, "auditor1", "AUDITOR1_PASSWORD")
    response = api.post(
        "/api/intake/artefact",
        files={"file": ("complaint_sample.pdf", PDF_SAMPLE.read_bytes(), "application/pdf")},
        headers=auditor,
    )
    assert response.status_code == 403


def test_unsupported_artefact_type_415(api):
    officer = _token(api, "officer1", "OFFICER1_PASSWORD")
    response = api.post(
        "/api/intake/artefact",
        files={"file": ("notes.txt", b"plain text, not an artefact", "text/plain")},
        headers=officer,
    )
    assert response.status_code == 415
    assert "unsupported artefact type" in response.json()["detail"]


def test_empty_upload_422(api):
    officer = _token(api, "officer1", "OFFICER1_PASSWORD")
    response = api.post(
        "/api/intake/artefact",
        files={"file": ("complaint_sample.pdf", b"", "application/pdf")},
        headers=officer,
    )
    assert response.status_code == 422
