#!/usr/bin/env python3
"""Generate the two committed synthetic ingest samples (SPEC 9.1).

Outputs, written to ``dataset/samples/`` by default:

- ``complaint_sample.pdf``: a one-page synthetic complaint letter with a
  real PDF text layer (exercises the pdfplumber path of
  ``paritran.engine.ingest_ocr.extract_text``).
- ``complaint_scan.png``: the same letter rendered onto a noisy image,
  simulating a scanned complaint (exercises the Tesseract OCR path).

Both documents plant the same known identifiers so NER accuracy over the
ingest path is measurable end to end:

- phone   9876543210
- UPI     fraudster@upi
- IP      203.0.113.7
- account 123456789012

SYNTHETIC ONLY, ZERO REAL PII: every name, address, amount and identifier
below is fictional, and each document carries a visible
"SYNTHETIC SAMPLE, ZERO REAL PII" line. No real tender, bidder, customer
or complainant data exists anywhere in this script or its outputs.

Deterministic generation: the PDF creation date is pinned (fpdf2 derives
its file ID from it) and the scan noise comes from ``random.Random(42)``,
so re-running this script byte-reproduces both committed binaries with
the pinned dependency versions (backend/requirements-m3-ner-ingest.txt).

Usage: python3 scripts/make_samples.py [--outdir dataset/samples]
"""

from __future__ import annotations

import argparse
import hashlib
import random
from datetime import datetime, timezone
from pathlib import Path

from fpdf import FPDF
from fpdf.enums import XPos, YPos
from PIL import Image, ImageDraw, ImageFont

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTDIR = REPO_ROOT / "dataset" / "samples"

# Pinned so the PDF (whose file ID hashes the creation date) is stable.
CREATION_DATE = datetime(2026, 1, 1, 0, 0, 0, tzinfo=timezone.utc)
NOISE_SEED = 42

# The identifiers planted in both documents, as (identifier, kind) pairs
# matching paritran.engine.ner.extract output.
PLANTED = {
    ("9876543210", "phone"),
    ("fraudster@upi", "upi"),
    ("203.0.113.7", "ipv4"),
    ("123456789012", "account"),
}

TITLE = "SYNTHETIC SAMPLE, ZERO REAL PII"

BODY_LINES = [
    "(Generated by scripts/make_samples.py; every detail below is fictional.)",
    "",
    "To: Station House Officer, Cyber Crime Police Station, Ahmedabad City",
    "Subject: Complaint regarding online payment fraud (synthetic sample)",
    "",
    "Respected Sir or Madam,",
    "",
    "I, Ramesh Kumar Patel, a fictional complainant residing at 14 Harmony",
    "Residency, Ahmedabad, wish to report an online fraud. On 3 June 2026 I",
    "received a call from mobile number 9876543210. The caller claimed to be",
    "a bank officer and persuaded me to confirm a one time password.",
    "",
    "Immediately afterwards Rs. 45,000 was debited from my savings account",
    "123456789012 held with a nationalised bank. The beneficiary shown on",
    "the transaction receipt was the UPI handle fraudster@upi. The bank's",
    "cyber cell informed me that the fraudulent session originated from the",
    "IP address 203.0.113.7.",
    "",
    "I request that my complaint be registered and the beneficiary account",
    "be frozen at the earliest.",
    "",
    "Yours faithfully,",
    "Ramesh Kumar Patel (fictional complainant)",
    "Date: 3 June 2026 (synthetic)",
]


def build_pdf(path: Path) -> None:
    """One-page complaint letter with a real text layer (pdfplumber path)."""
    pdf = FPDF(format="A4")
    pdf.set_creation_date(CREATION_DATE)
    pdf.set_margins(20, 20)
    pdf.add_page()
    pdf.set_font("Helvetica", style="B", size=13)
    pdf.cell(0, 8, TITLE, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(2)
    pdf.set_font("Helvetica", size=11)
    for line in BODY_LINES:
        pdf.cell(0, 6, line, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.output(str(path))


def build_scan(path: Path) -> None:
    """The same letter as a noisy PNG, simulating a scan (OCR path)."""
    rng = random.Random(NOISE_SEED)
    margin, step = 70, 42
    width = 1500
    height = margin * 2 + step * (len(BODY_LINES) + 2)
    image = Image.new("RGB", (width, height), (252, 252, 250))
    draw = ImageDraw.Draw(image)

    # Pillow's embedded scalable default font: no system font dependency,
    # identical rendering on any host, which keeps the output deterministic.
    title_font = ImageFont.load_default(size=34)
    body_font = ImageFont.load_default(size=28)

    y = margin
    draw.text((margin, y), TITLE, fill=(15, 15, 15), font=title_font)
    y += step * 2
    for line in BODY_LINES:
        if line:
            draw.text((margin, y), line, fill=(25, 25, 25), font=body_font)
        y += step

    # Scan artefacts, all from the seeded RNG: speckle plus faint streaks.
    for _ in range(3500):
        x = rng.randrange(width)
        yy = rng.randrange(height)
        g = rng.randrange(120, 210)
        image.putpixel((x, yy), (g, g, g))
    for _ in range(3):
        yy = rng.randrange(height)
        g = rng.randrange(200, 235)
        draw.line((0, yy, width, yy), fill=(g, g, g), width=1)

    image.save(path, format="PNG")


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--outdir",
        type=Path,
        default=DEFAULT_OUTDIR,
        help="output directory (default: dataset/samples)",
    )
    args = parser.parse_args()
    args.outdir.mkdir(parents=True, exist_ok=True)

    pdf_path = args.outdir / "complaint_sample.pdf"
    png_path = args.outdir / "complaint_scan.png"
    build_pdf(pdf_path)
    build_scan(png_path)
    for p in (pdf_path, png_path):
        print(f"{_sha256(p)}  {p}")


if __name__ == "__main__":
    main()
